<?php

$LDC_COUNTRIES = [
    'AFGHANISTAN','BANGLADESH','BHUTAN','CAMBODIA','LAO PDR','MYANMAR','NEPAL','YEMEN',
    'ANGOLA','BENIN','BURKINA FASO','BURUNDI','CENTRAL AFRICAN REPUBLIC','CHAD',
    'COMOROS','DEMOCRATIC REPUBLIC OF THE CONGO','DJIBOUTI','ERITREA','ETHIOPIA',
    'GAMBIA','GUINEA','GUINEA-BISSAU','LESOTHO','LIBERIA','MADAGASCAR','MALAWI',
    'MALI','MAURITANIA','MOZAMBIQUE','NIGER','RWANDA','SENEGAL','SIERRA LEONE',
    'SOMALIA','SOUTH SUDAN','SUDAN','TANZANIA','TOGO','UGANDA','ZAMBIA',
    'KIRIBATI','SOLOMON ISLANDS','TUVALU','HAITI'
];

$SIDS_COUNTRIES = [
    'ANTIGUA AND BARBUDA','BAHAMAS','BARBADOS','BELIZE','CUBA','DOMINICA',
    'DOMINICAN REPUBLIC','GRENADA','GUYANA','HAITI','JAMAICA','SAINT LUCIA',
    'SAINT VINCENT AND THE GRENADINES','SURINAME','TRINIDAD AND TOBAGO',
    'FIJI','KIRIBATI','MARSHALL ISLANDS','MICRONESIA','NAURU','PALAU',
    'PAPUA NEW GUINEA','SAMOA','SOLOMON ISLANDS','TONGA','TUVALU','VANUATU',
    'MALDIVES','MAURITIUS','SEYCHELLES','CABO VERDE','SAO TOME AND PRINCIPE',
    'COMOROS','TIMOR-LESTE','SINGAPORE','BAHRAIN'
];